### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by melgor** [KevinMusgrave/powerful_benchmarker#1]
Hi,
I want to reproduce one of the results from your CSV file. I downloaded triplet config. How can I feed it into benchmarker?

I found one way:
- copy all configs to related confing-directory (mean config_eval.yaml to configs/config_eval/) and rename to `triplet.yaml`
- run by command
```bash
python run.py --experiment_name triplet_v1 --config_general default triplet --config_models default triplet --config_optimizers default triplet --config_loss_and_miners default triplet --config_transforms default triplet --config_eval default triplet
```

I need to have two configs (default and triplet) as ex. `eval_pca` is not defined in `triplet` configs. 
Is this the correct way of reproducing the results? Or there exist better way?

**Comment by KevinMusgrave** [comment]
Thanks for your interest in this project! I just pushed the following changes to address this problem. Here is how you can reproduce results now:

1) In the benchmark spreadsheet, click on the google drive link under the "config files" column.
2) Download the folders you want (for example cub200_old_approach_triplet_batch_all), into some folder on your computer. For example, I downloaded into /home/tkm45/experiments_to_reproduce
3) Then run:
`python run.py --reproduce_results /home/tkm45/experiments_to_reproduce/cub200_old_approach_triplet_batch_all --experiment_name cub200_old_approach_triplet_batch_all_reproduced`

You cannot override complex (nested) config options at the command line in this case. But you can still override non-nested options. For example, you might like to use a different number of workers for your dataloaders:

`python run.py --reproduce_results /home/tkm45/experiments_to_reproduce/cub200_old_approach_triplet_batch_all --experiment_name cub200_old_approach_triplet_batch_all_reproduced \
--dataloader_num_workers 6 \
--eval_dataloader_num_workers 6`

Things still remaining to fix:
In the configs folder of cub200_old_approach_triplet_batch_all, you'll see a subfolder called resume_training_config_diffs_1. This just indicates that I resumed training and that I changed num_epochs_train to 60 (it was originally 50). At the moment, the "reproduce_results" option does not look for these diff folders. So you may need to copy any changes from the diff folder into the config file. From what I remember, the only parameter I ever changed when resuming training was num_epochs_train.

Let me know if it works for you!

**Comment by KevinMusgrave** [comment]
My latest commits fix the config_diff issue. The reproduce_results flag parses the config_diff folders so that training proceeds exactly as it did in the original experiment.
